#!/usr/bin/env node

var rs = require('robotskirt')
  , fs = require('fs')
  , util = require('util');

var flags = ~0;
var renderer = new rs.HtmlRenderer();
var files = process.argv.slice(2);
files.forEach(function(filename){
    fs.readFile('readme.md', 'utf8', function (err, data) {
      var parser = new rs.Markdown(renderer, flags);
	  util.puts(parser.render(data));
    })
});